services:
  api:
    build: .
    container_name: blog-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/blogdb
    volumes:
      - .:/app
    command: node server.js

  mongo:
    image: mongo:6
    container_name: mongo-blog
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
